package org.nj2pc.oem.commsplan;

import org.openpdf.text.Document;
import org.openpdf.text.Element;
import org.openpdf.text.Font;
import org.openpdf.text.FontFactory;
import org.openpdf.text.PageSize;
import org.openpdf.text.Paragraph;
import org.openpdf.text.Phrase;
import org.openpdf.text.pdf.PdfPCell;
import org.openpdf.text.pdf.PdfPTable;
import org.openpdf.text.pdf.PdfWriter;
import org.nj2pc.oem.incident.Incident;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class Ics205PdfService {

    private static final DateTimeFormatter DATE_TIME_FMT =
            DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm").withZone(ZoneId.systemDefault());

    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
    private static final Font HEADER_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9);
    private static final Font LABEL_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 7);
    private static final Font VALUE_FONT = FontFactory.getFont(FontFactory.HELVETICA, 9);
    private static final Font TABLE_HEADER_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 7);
    private static final Font TABLE_CELL_FONT = FontFactory.getFont(FontFactory.HELVETICA, 7);
    private static final Font SMALL_ITALIC_FONT = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 7);

    private final CommunicationPlanService communicationPlanService;
    private final CommunicationChannelRepository communicationChannelRepository;

    public Ics205PdfService(CommunicationPlanService communicationPlanService,
                            CommunicationChannelRepository communicationChannelRepository) {
        this.communicationPlanService = communicationPlanService;
        this.communicationChannelRepository = communicationChannelRepository;
    }

    @Transactional(readOnly = true)
    public byte[] generate(Long planId) {
        CommunicationPlan plan = communicationPlanService.getPlanOrThrow(planId);
        List<CommunicationChannel> channels = communicationChannelRepository
                .findByPlanIdOrderByChannelNumberAsc(planId);

        Document document = new Document(PageSize.LETTER.rotate(), 24, 24, 24, 24);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(document, out);
            document.open();

            document.add(buildTitle());
            document.add(spacer());
            document.add(buildHeaderTable(plan));
            document.add(spacer());
            document.add(sectionLabel("3. Basic Radio Channel Utilization"));
            document.add(buildChannelTable(channels));
            document.add(spacer());
            document.add(sectionLabel("4. Special Instructions"));
            document.add(new Paragraph(nullToDash(plan.getSpecialInstructions()), VALUE_FONT));
            document.add(spacer());
            document.add(buildSignatureTable(plan));
            document.add(spacer());
            document.add(new Paragraph(
                    "ICS 205 | " + plan.getName() + " | Generated by NJ2PC-OEM", SMALL_ITALIC_FONT));

            document.close();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate ICS-205 PDF", e);
        }

        return out.toByteArray();
    }

    private Paragraph buildTitle() {
        Paragraph title = new Paragraph("COMMUNICATIONS PLAN (ICS 205)", TITLE_FONT);
        title.setAlignment(Element.ALIGN_CENTER);
        return title;
    }

    private PdfPTable buildHeaderTable(CommunicationPlan plan) {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        try {
            table.setWidths(new float[]{1f, 1f});
        } catch (Exception ignored) {
            // widths array size always matches column count here
        }

        String incidentNames = plan.getIncidents().stream()
                .map(Incident::getName)
                .sorted(Comparator.naturalOrder())
                .collect(Collectors.joining(", "));
        if (incidentNames.isBlank()) {
            incidentNames = plan.getName();
        }

        String operationalPeriod = formatRange(plan.getOperationalPeriodStart(), plan.getOperationalPeriodEnd());

        table.addCell(labeledCell("1. Incident Name", incidentNames));
        table.addCell(labeledCell("2. Operational Period", operationalPeriod));
        return table;
    }

    private PdfPTable buildChannelTable(List<CommunicationChannel> channels) {
        String[] headers = {
                "Zone/Grp", "Ch #", "Function", "Channel Name", "Assignment",
                "RX Freq", "RX Tone/NAC", "TX Freq", "TX Tone/NAC", "Mode", "Remarks"
        };
        float[] widths = {0.6f, 0.4f, 0.9f, 1.1f, 1.3f, 0.7f, 0.9f, 0.7f, 0.9f, 0.4f, 1.3f};

        PdfPTable table = new PdfPTable(headers.length);
        table.setWidthPercentage(100);
        try {
            table.setWidths(widths);
        } catch (Exception ignored) {
            // widths array size always matches column count here
        }

        for (String header : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(header, TABLE_HEADER_FONT));
            cell.setBackgroundColor(new Color(230, 230, 230));
            cell.setPadding(3f);
            table.addCell(cell);
        }

        if (channels.isEmpty()) {
            PdfPCell empty = new PdfPCell(new Phrase("No channels defined", TABLE_CELL_FONT));
            empty.setColspan(headers.length);
            empty.setPadding(4f);
            table.addCell(empty);
            return table;
        }

        for (CommunicationChannel c : channels) {
            addBodyCell(table, c.getZoneGroup());
            addBodyCell(table, String.valueOf(c.getChannelNumber()));
            addBodyCell(table, c.getFunction());
            addBodyCell(table, c.getChannelName());
            addBodyCell(table, nullToDash(c.getAssignment()));
            addBodyCell(table, nullToDash(c.getRxFrequency()));
            addBodyCell(table, nullToDash(c.getRxTone()));
            addBodyCell(table, nullToDash(c.getTxFrequency()));
            addBodyCell(table, nullToDash(c.getTxTone()));
            addBodyCell(table, c.getMode().name().substring(0, 1));
            addBodyCell(table, nullToDash(c.getRemarks()));
        }
        return table;
    }

    private PdfPTable buildSignatureTable(CommunicationPlan plan) {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        try {
            table.setWidths(new float[]{1f, 1f});
        } catch (Exception ignored) {
            // widths array size always matches column count here
        }

        String preparedBy = joinNameCallsign(plan.getPreparedByName(), plan.getPreparedByCallsign());
        String approvedBy = joinNameCallsign(plan.getApprovedByName(), plan.getApprovedByCallsign());

        table.addCell(labeledCell("5. Prepared by (Communications Unit)", preparedBy));
        table.addCell(labeledCell("6. Date/Time", formatInstant(plan.getPreparedAt())));
        table.addCell(labeledCell("7. Approved by (Incident Communications Center Manager)", approvedBy));
        table.addCell(labeledCell("8. Date/Time", formatInstant(plan.getApprovedAt())));
        return table;
    }

    private void addBodyCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, TABLE_CELL_FONT));
        cell.setPadding(3f);
        table.addCell(cell);
    }

    private PdfPCell labeledCell(String label, String value) {
        PdfPCell cell = new PdfPCell();
        cell.setPadding(5f);
        Paragraph p = new Paragraph();
        p.add(new Phrase(label + "\n", LABEL_FONT));
        p.add(new Phrase(value == null || value.isBlank() ? "—" : value, VALUE_FONT));
        cell.addElement(p);
        return cell;
    }

    private Paragraph sectionLabel(String text) {
        return new Paragraph(text, HEADER_FONT);
    }

    private Paragraph spacer() {
        return new Paragraph(" ", VALUE_FONT);
    }

    private String nullToDash(String value) {
        return value == null || value.isBlank() ? "—" : value;
    }

    private String joinNameCallsign(String name, String callsign) {
        if ((name == null || name.isBlank()) && (callsign == null || callsign.isBlank())) {
            return "—";
        }
        if (callsign == null || callsign.isBlank()) {
            return name;
        }
        if (name == null || name.isBlank()) {
            return callsign;
        }
        return name + " (" + callsign + ")";
    }

    private String formatInstant(Instant instant) {
        return instant == null ? "—" : DATE_TIME_FMT.format(instant);
    }

    private String formatRange(Instant start, Instant end) {
        if (start == null && end == null) return "—";
        if (start != null && end != null) {
            return "From: " + DATE_TIME_FMT.format(start) + "  To: " + DATE_TIME_FMT.format(end);
        }
        if (start != null) {
            return "From: " + DATE_TIME_FMT.format(start);
        }
        return "To: " + DATE_TIME_FMT.format(end);
    }
}
