apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hams
  labels:
    app.kubernetes.io/name: nj2pc-oem-backend
    homelab/stack: nj2pc-oem
spec:
  selector:
    app.kubernetes.io/name: nj2pc-oem-backend
  ports:
    - port: 8080
      targetPort: 8080
