apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nj2pc-oem
  namespace: hams
  labels:
    app.kubernetes.io/name: nj2pc-oem
    homelab/stack: nj2pc-oem
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: emcomms.in.alybadawy.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
