package org.nj2pc.oem.operator;

public enum Permission {
    OPERATOR_LIST,
    OPERATOR_MANAGE_PERMISSIONS,
    OPERATOR_CREATE,
    INCIDENT_CREATE,
    INCIDENT_VIEW_ALL,
    INCIDENT_EDIT_ALL,
    RESOURCE_TYPE_MANAGE,
    RESOURCE_MANAGE_ALL,
    LOG_VIEW
}
