package org.nj2pc.oem.operator;

public enum Permission {
    OPERATOR_LIST,
    OPERATOR_MANAGE_PERMISSIONS,
    OPERATOR_CREATE,
    OPERATOR_EDIT,
    OPERATOR_VIEW_CONTACT,
    INCIDENT_CREATE,
    INCIDENT_VIEW_ALL,
    INCIDENT_EDIT_ALL,
    RESOURCE_TYPE_MANAGE,
    RESOURCE_MANAGE_ALL,
    RESOURCE_ASSIGN_OWNER,
    VEHICLE_VIEW_DETAILS,
    OPERATOR_ROLE_MANAGE,
    LOG_VIEW,
    COMMS_PLAN_MANAGE
}
